#!/bin/bash
###############################################################################
# Author: Victor Yap <victor.yap@alumni.concordia.ca>
# Purpose:
#   An easier way to do arbitrary "transparent multi-hop SSH".
# Assumptions:
#   You've configured "sshgw" to resolve to your host's actual hostname.
###############################################################################
set -o nounset
set -o errexit
ssh $1 -p $2 -o="ProxyCommand ssh sshgw nc %h %p"
